version: '3.8'

name: readme-project
services:
  workspace:
    build:
      context: .
      dockerfile: ../.devcontainer/Dockerfile
    container_name: readme-workspace
    depends_on:
      - mongodb
      - postgresdb
      - rabbitmq
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - '8080:8080'
    env_file:
      - ../.devcontainer/devcontainer.env

  mongodb:
    env_file:
      - ../.devcontainer/devcontainer.env

  postgresdb:
    env_file:
      - ../.devcontainer/devcontainer.env

  mongo-express:
    env_file:
      - ../.devcontainer/devcontainer.env
