version: '3.8'

name: readme-project
services:
  workspace:
    build:
      context: .
      dockerfile: ../.devcontainer/Dockerfile
    container_name: readme-workspace
    depends_on:
      - mongodb
      - postgresdb
      - rabbitmq
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - '8080:8080'
    env_file:
      - ../.devcontainer/devcontainer.env

  mongodb:
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: readme-users

  postgresdb:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: readme-blog

  rabbitmq:
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  fakesmtp:
    restart: unless-stopped

  mongo-express:
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  pgadmin:
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
